version: '3.9'
services:
  web:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    environment:
      NODE_ENV: development